package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <style type=\"text/css\">\r\n");
      out.write(" \r\n");
      out.write(" body{\r\n");
      out.write("  font-family: Trebuchet MS, Lucida Sans Unicode, Arial, sans-serif;\r\n");
      out.write("  margin-top:0px;\r\n");
      out.write("     \r\n");
      out.write(" }\r\n");
      out.write(" .bodyText{\r\n");
      out.write("  padding-left:10px;\r\n");
      out.write("  padding-right:10px;\r\n");
      out.write("  border-top:1px solid #000000; \r\n");
      out.write(" }\r\n");
      out.write(" .bodyText p{\r\n");
      out.write("  margin-top:8px;\r\n");
      out.write(" }\r\n");
      out.write(" #mainContainer{\r\n");
      out.write("  width:760px;\r\n");
      out.write("  height:600px;\r\n");
      out.write("  border:6px solid #000000;\r\n");
      out.write("  margin:1 auto;\r\n");
      out.write("  background-image:url('flight.bmp');\r\n");
      out.write("  background-repeat:no-repeat;\r\n");
      out.write("  padding-top:85px;   \r\n");
      out.write(" }\r\n");
      out.write(" #mainMenu{\r\n");
      out.write("  background-color: #fff; /* Background color of main menu */\r\n");
      out.write("  //font-family: Trebuchet MS, Lucida Sans Unicode, Arial, sans-serif; /* Fonts of main menu items */\r\n");
      out.write("  \r\n");
      out.write("  font-size:1.1em; /* Font size of main menu items */\r\n");
      out.write("  border-bottom:1px solid #000000; /* Bottom border of main menu */\r\n");
      out.write("  height:50px; /* Height of main menu */\r\n");
      out.write("  \r\n");
      out.write("  position:relative; /* Don't change this position attribute */\r\n");
      out.write("  \r\n");
      out.write(" }\r\n");
      out.write(" #mainMenu a{\r\n");
      out.write("  padding-left:5px;<br> /* Spaces at the left of main menu items */\r\n");
      out.write("  padding-right:555px; /* Spaces at the right of main menu items */\r\n");
      out.write("  font-weight:Berlin Sans FB;\r\n");
      out.write("  /* Don't change these two options */\r\n");
      out.write("  position:absolute;\r\n");
      out.write("  bottom:-1px; /* Change this value to -2px if you're not using a strict doctype */\r\n");
      out.write(" }\r\n");
      out.write(" #submenu{  \r\n");
      out.write("  font-family: Trebuchet MS, Lucida Sans Unicode, Arial, sans-serif; /* Font  of sub menu items */\r\n");
      out.write("  background-color:#E2EBED; /* Background color of sub menu items */\r\n");
      out.write("  \r\n");
      out.write("  width:100%; /* Don't change this option */\r\n");
      out.write("  \r\n");
      out.write(" } \r\n");
      out.write(" #submenu div{\r\n");
      out.write("  white-space:nowrap; /* Don't change this option */\r\n");
      out.write("  \r\n");
      out.write(" }\r\n");
      out.write(" /*\r\n");
      out.write(" Style attributes of active menu item \r\n");
      out.write(" */\r\n");
      out.write(" #mainMenu .activeMenuItem{\r\n");
      out.write("  /* Border options */\r\n");
      out.write("  border-left:1px solid #0E0E;\r\n");
      out.write("  border-top:1px solid #0FF0;\r\n");
      out.write("  border-right:1px solid #0BB00;  \r\n");
      out.write("  background-color: #AABBFF; /* Background color */\r\n");
      out.write("  \r\n");
      out.write("  cursor:pointer; /* Cursor like a hand when the user moves the mouse over the menu item */\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" #mainMenu .activeMenuItem img{\r\n");
      out.write("  position:absolute;\r\n");
      out.write("  bottom:1px;\r\n");
      out.write("  right:1px;\r\n");
      out.write(" }\r\n");
      out.write("  \r\n");
      out.write(" /*\r\n");
      out.write(" Style attributes of inactive menu items\r\n");
      out.write(" */\r\n");
      out.write(" #mainMenu .inactiveMenuItem{  \r\n");
      out.write("  color: #00FF; /* Text color */\r\n");
      out.write("  cursor:pointer; /* Cursor like a hand when the user moves the mouse over the menu item */\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" #submenu a{ \r\n");
      out.write("  text-decoration:underline; /* No underline on sub menu items - use text-decoration:underline; if you want the links to be underlined */\r\n");
      out.write("  padding-left:10px; /* Space at the left of each sub menu item */\r\n");
      out.write("  padding-right:5px; /* Space at the right of each sub menu item */\r\n");
      out.write("  color: #000; /* Text color */\r\n");
      out.write("  font-size:1.0em; \r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" #submenu a:hover{\r\n");
      out.write("  color: #FFEE; /* Red color when the user moves the mouse over sub menu items */\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" </style>\r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write(" \r\n");
      out.write(" var menuAlignment = 'left'; // Align menu to the left or right?  \r\n");
      out.write(" var topMenuSpacer = 4; // Horizontal space(pixels) between the main menu items \r\n");
      out.write(" var activateSubOnClick = false; // if true-> Show sub menu items on click, if false, show submenu items onmouseover\r\n");
      out.write(" var leftAlignSubItems = false;  // left align sub items t\r\n");
      out.write(" \r\n");
      out.write(" var activeMenuItem = false; // Don't change this option. It should initially be false\r\n");
      out.write(" var activeTabIndex = 0; // Index of initial active tab (0 = first tab) - If the value below is set to true, it will override this one.\r\n");
      out.write(" var rememberActiveTabByCookie = true; // Set it to true if you want to be able to save active tab as cookie\r\n");
      out.write(" \r\n");
      out.write(" var MSIE = navigator.userAgent.indexOf('MSIE')>=0?true:false;\r\n");
      out.write(" var Opera = navigator.userAgent.indexOf('Opera')>=0?true:false;\r\n");
      out.write(" var navigatorVersion = navigator.appVersion.replace(/.*?MSIE ([0-9]\\.[0-9]).*/g,'$1')/1;\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write(" function Get_Cookie(name) { \r\n");
      out.write("     var start = document.cookie.indexOf(name+\"=\"); \r\n");
      out.write("     var len = start+name.length+1; \r\n");
      out.write("     if ((!start) && (name != document.cookie.substring(5,name.length))) return null; \r\n");
      out.write("     if (start == -1) return null; \r\n");
      out.write("     var end = document.cookie.indexOf(\";\",len); \r\n");
      out.write("     if (end == -1) end = document.cookie.length; \r\n");
      out.write("     return unescape(document.cookie.substring(len,end)); \r\n");
      out.write("  } \r\n");
      out.write("  // This function has been slightly modified\r\n");
      out.write("  function Set_Cookie(name,value,expires,path,domain,secure) { \r\n");
      out.write("   expires = expires * 60*60*24*1000;\r\n");
      out.write("   var today = new Date();\r\n");
      out.write("   var expires_date = new Date( today.getTime() + (expires) );\r\n");
      out.write("      var cookieString = name + \"=\" +escape(value) + \r\n");
      out.write("         ( (expires) ? \";expires=\" + expires_date.toGMTString() : \"\") + \r\n");
      out.write("         ( (path) ? \";path=\" + path : \"\") + \r\n");
      out.write("         ( (domain) ? \";domain=\" + domain : \"\") + \r\n");
      out.write("         ( (secure) ? \";secure\" : \"\"); \r\n");
      out.write("      document.cookie = cookieString; \r\n");
      out.write("  } \r\n");
      out.write(" \r\n");
      out.write(" function showHide()\r\n");
      out.write(" {\r\n");
      out.write("  if(activeMenuItem){\r\n");
      out.write("   activeMenuItem.className = 'inactiveMenuItem';  \r\n");
      out.write("   var theId = activeMenuItem.id.replace(/[^0-9]/g,'');\r\n");
      out.write("   document.getElementById('submenu_'+theId).style.display='none';\r\n");
      out.write("   var img = activeMenuItem.getElementsByTagName('IMG');\r\n");
      out.write("   if(img.length>0)img[0].style.display='none';   \r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  var img = this.getElementsByTagName('IMG');\r\n");
      out.write("  if(img.length>0)img[0].style.display='inline';\r\n");
      out.write("    \r\n");
      out.write("   activeMenuItem = this;  \r\n");
      out.write("  this.className = 'activeMenuItem';\r\n");
      out.write("  var theId = this.id.replace(/[^0-9]/g,'');\r\n");
      out.write("  document.getElementById('submenu_'+theId).style.display='block';\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  if(rememberActiveTabByCookie){\r\n");
      out.write("   Set_Cookie('dhtmlgoodies_tab_menu_tabIndex','index: ' + (theId-1),100);\r\n");
      out.write("  }\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" function initMenu()\r\n");
      out.write(" {\r\n");
      out.write("  var mainMenuObj = document.getElementById('mainMenu');\r\n");
      out.write("  var menuItems = mainMenuObj.getElementsByTagName('A');\r\n");
      out.write("  if(document.all){\r\n");
      out.write("   mainMenuObj.style.visibility = 'hidden';\r\n");
      out.write("   document.getElementById('submenu').style.visibility='hidden';\r\n");
      out.write("  }  \r\n");
      out.write("  if(rememberActiveTabByCookie){\r\n");
      out.write("   var cookieValue = Get_Cookie('dhtmlgoodies_tab_menu_tabIndex') + '';\r\n");
      out.write("   cookieValue = cookieValue.replace(/[^0-9]/g,'');\r\n");
      out.write("   if(cookieValue.length>0 && cookieValue<menuItems.length){\r\n");
      out.write("    activeTabIndex = cookieValue/1;\r\n");
      out.write("   }   \r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  var currentLeftPos = 15;\r\n");
      out.write("  for(var no=0;no<menuItems.length;no++){   \r\n");
      out.write("   if(activateSubOnClick)menuItems[no].onclick = showHide; else menuItems[no].onmouseover = showHide;\r\n");
      out.write("   menuItems[no].id = 'mainMenuItem' + (no+1);\r\n");
      out.write("   if(menuAlignment=='left')\r\n");
      out.write("    menuItems[no].style.left = currentLeftPos + 'px';\r\n");
      out.write("   else\r\n");
      out.write("    menuItems[no].style.right = currentLeftPos + 'px';\r\n");
      out.write("   currentLeftPos = currentLeftPos + menuItems[no].offsetWidth + topMenuSpacer; \r\n");
      out.write("   \r\n");
      out.write("   var img = menuItems[no].getElementsByTagName('IMG');\r\n");
      out.write("   if(img.length>0){\r\n");
      out.write("    img[0].style.display='none';\r\n");
      out.write("    if(MSIE && !Opera && navigatorVersion<7){\r\n");
      out.write("     img[0].style.bottom = '-1px';\r\n");
      out.write("     img[0].style.right = '-1px';\r\n");
      out.write("    }\r\n");
      out.write("   }\r\n");
      out.write("      \r\n");
      out.write("   if(no==activeTabIndex){\r\n");
      out.write("    menuItems[no].className='activeMenuItem';\r\n");
      out.write("    activeMenuItem = menuItems[no];\r\n");
      out.write("    var img = activeMenuItem.getElementsByTagName('');\r\n");
      out.write("    if(img.length>0)img[0].style.display='inline'; \r\n");
      out.write("       \r\n");
      out.write("   }else menuItems[no].className='inactiveMenuItem';\r\n");
      out.write("   if(!document.all)menuItems[no].style.bottom = '-1px';\r\n");
      out.write("   if(MSIE && navigatorVersion < 6)menuItems[no].style.bottom = '-2px';\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("  }  \r\n");
      out.write("  \r\n");
      out.write("  var mainMenuLinks = mainMenuObj.getElementsByTagName('A');\r\n");
      out.write("  \r\n");
      out.write("  var subCounter = 1;\r\n");
      out.write("  var parentWidth = mainMenuObj.offsetWidth;\r\n");
      out.write("  while(document.getElementById('submenu_' + subCounter)){\r\n");
      out.write("   var subItem = document.getElementById('submenu_' + subCounter);\r\n");
      out.write("   \r\n");
      out.write("   if(leftAlignSubItems){\r\n");
      out.write("    // No action\r\n");
      out.write("   }else{       \r\n");
      out.write("    var leftPos = mainMenuLinks[subCounter-1].offsetLeft;\r\n");
      out.write("    document.getElementById('submenu_'+subCounter).style.paddingLeft =  leftPos + 'px';\r\n");
      out.write("    subItem.style.position ='absolute';\r\n");
      out.write("    if(subItem.offsetWidth > parentWidth){\r\n");
      out.write("     leftPos = leftPos - Math.max(0,subItem.offsetWidth-parentWidth);  \r\n");
      out.write("    }\r\n");
      out.write("    subItem.style.paddingLeft =  leftPos + 'px';\r\n");
      out.write("    subItem.style.position ='static';\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("   }\r\n");
      out.write("   if(subCounter==(activeTabIndex+1)){\r\n");
      out.write("    subItem.style.display='block';\r\n");
      out.write("   }else{\r\n");
      out.write("    subItem.style.display='none';\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   subCounter++;\r\n");
      out.write("  }\r\n");
      out.write("  if(document.all){\r\n");
      out.write("   mainMenuObj.style.visibility = 'visible';\r\n");
      out.write("   document.getElementById('submenu').style.visibility='visible';\r\n");
      out.write("  }  \r\n");
      out.write("  document.getElementById('submenu').style.display='Red';\r\n");
      out.write(" }\r\n");
      out.write(" window.onload = initMenu; \r\n");
      out.write(" function openCal()\r\n");
      out.write(" {\r\n");
      out.write("  window.open(\"New.jsp\",40,70);\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- This is the start of the menu -->\r\n");
      out.write("<div id=\"mainMenu\">\r\n");
      out.write(" <a>AirIndia</a><br><br><br>\r\n");
      out.write(" <a>KingFisher</a><br><br><br>\r\n");
      out.write(" <a>TravelData</a><br><br><br>\r\n");
      out.write(" <a>AmericanAirLines</a><br><br><br>\r\n");
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"submenu\">\r\n");
      out.write(" <!-- The first sub menu -->\r\n");
      out.write(" <div id=\"submenu_1\">\r\n");
      out.write("  <a href onmouseover=\"javascript:openCal()\" >FlightMap\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</a>\r\n");
      out.write(" <!-- <br> <a href=\"javascript:openCal()\">Delhi\r\n");
      out.write(" </a>\r\n");
      out.write("  <br><a href=\"javascript:openCal()\">Mumbai</a> -->\r\n");
      out.write(" </div>\r\n");
      out.write(" <!-- Second sub menu -->\r\n");
      out.write(" <div id=\"submenu_2\">\r\n");
      out.write("  <a href=\"javascript:openCal()\">MoreInfo<textarea id=\"flight1\" rows=\"5\" cols=\"30\" style='visibility;'>\r\n");
      out.write("Flihht from Delhi\r\n");
      out.write(" to Hyderabad time \r\n");
      out.write("Evening  4 pm\r\n");
      out.write("</textarea>\r\n");
      out.write("  </a><br>\r\n");
      out.write("  <!-- <a href=\"javascript:openCal()\">Hyderabad</a><br>\r\n");
      out.write("  <a href=\"javascript:openCal()\">Bangalore</a><br> -->\r\n");
      out.write(" </div>\r\n");
      out.write(" <!-- Third sub menu -->\r\n");
      out.write(" <div id=\"submenu_3\">\r\n");
      out.write(" <a href=\"javascript:openCal()\">PassingerData</a><br>\r\n");
      out.write("  <a href=\"javascript:openCal()\">FlightData</a><br>\r\n");
      out.write("  <a href  onmouseover=\"javascript:openCal()\">DisplayMap <iframe src=\"my.jsp\" \r\n");
      out.write(" style=\"float: center; \r\n");
      out.write(" width: 300px; height: 200px; \r\n");
      out.write(" margin-left: 12px; border: 1px solid black;\" \r\n");
      out.write(" name=\"#boogiejack\">\r\n");
      out.write("</iframe> </a>\r\n");
      out.write("\r\n");
      out.write(" </div>\r\n");
      out.write(" <!-- Fourth sub menu -->\r\n");
      out.write(" <div id=\"submenu_4\">\r\n");
      out.write("  <a href=\"javascript:openCal()\">Sidny</a><br>\r\n");
      out.write("  <a href=\"javascript:openCal()\">New Delhi</a><br>\r\n");
      out.write("  <a href=\"javascript:openCal()\">London</a><br>\r\n");
      out.write("  <a href=\"javascript:openCal()\">Moscow</a><br>\r\n");
      out.write("  <a href=\"javascript:openCal()\">Beijil</a><br>\r\n");
      out.write("  <a href=\"javascript:openCal()\">TokyoIslamabad</a><br>\r\n");
      out.write("\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
