package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tfont-family: Trebuchet MS, Lucida Sans Unicode, Arial, sans-serif;\r\n");
      out.write("\t\tmargin-top:0px;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.bodyText{\r\n");
      out.write("\t\tpadding-left:10px;\r\n");
      out.write("\t\tpadding-right:10px;\r\n");
      out.write("\t\tborder-top:1px solid #000000;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.bodyText p{\r\n");
      out.write("\t\tmargin-top:8px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#mainContainer{\r\n");
      out.write("\t\twidth:760px;\r\n");
      out.write("\t\theight:600px;\r\n");
      out.write("\t\tborder:6px solid #000000;\r\n");
      out.write("\t\tmargin:1 auto;\r\n");
      out.write("\t\tbackground-image:url('flight.bmp');\r\n");
      out.write("\t\tbackground-repeat:no-repeat;\r\n");
      out.write("\t\tpadding-top:85px;\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#mainMenu{\r\n");
      out.write("\t\tbackground-color: #fff;\t/* Background color of main menu */\r\n");
      out.write("\t\t//font-family: Trebuchet MS, Lucida Sans Unicode, Arial, sans-serif;\t/* Fonts of main menu items */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfont-size:0.9em;\t/* Font size of main menu items */\r\n");
      out.write("\t\tborder-bottom:1px solid #000000;\t/* Bottom border of main menu */\r\n");
      out.write("\t\theight:30px;\t/* Height of main menu */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tposition:relative;\t/* Don't change this position attribute */\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#mainMenu a{\r\n");
      out.write("\t\tpadding-left:5px;\t/* Spaces at the left of main menu items */\r\n");
      out.write("\t\tpadding-right:5px;\t/* Spaces at the right of main menu items */\r\n");
      out.write("\t\tfont-weight:italic;\r\n");
      out.write("\t\t/* Don't change these two options */\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\tbottom:-1px;\t/* Change this value to -2px if you're not using a strict doctype */\r\n");
      out.write("\t}\r\n");
      out.write("\t#submenu{\t\t\r\n");
      out.write("\t\tfont-family: Trebuchet MS, Lucida Sans Unicode, Arial, sans-serif;\t/* Font  of sub menu items */\r\n");
      out.write("\t\tbackground-color:#E2EBED;\t/* Background color of sub menu items */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\twidth:100%;\t/* Don't change this option */\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\t\r\n");
      out.write("\t#submenu div{\r\n");
      out.write("\t\twhite-space:nowrap;\t/* Don't change this option */\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t/*\r\n");
      out.write("\tStyle attributes of active menu item \r\n");
      out.write("\t*/\r\n");
      out.write("\t#mainMenu .activeMenuItem{\r\n");
      out.write("\t\t/* Border options */\r\n");
      out.write("\t\tborder-left:1px solid #0E0E;\r\n");
      out.write("\t\tborder-top:1px solid #0FF0;\r\n");
      out.write("\t\tborder-right:1px solid #0BB00;\t\t\r\n");
      out.write("\t\tbackground-color: #AABBFF;\t/* Background color */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcursor:pointer;\t/* Cursor like a hand when the user moves the mouse over the menu item */\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#mainMenu .activeMenuItem img{\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\tbottom:0px;\r\n");
      out.write("\t\tright:0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t/*\r\n");
      out.write("\tStyle attributes of inactive menu items\r\n");
      out.write("\t*/\r\n");
      out.write("\t#mainMenu .inactiveMenuItem{\t\t\r\n");
      out.write("\t\tcolor: #00FF;\t/* Text color */\r\n");
      out.write("\t\tcursor:pointer;\t/* Cursor like a hand when the user moves the mouse over the menu item */\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#submenu a{\t\r\n");
      out.write("\t\ttext-decoration:underline;\t/* No underline on sub menu items - use text-decoration:underline; if you want the links to be underlined */\r\n");
      out.write("\t\tpadding-left:10px;\t/* Space at the left of each sub menu item */\r\n");
      out.write("\t\tpadding-right:5px;\t/* Space at the right of each sub menu item */\r\n");
      out.write("\t\tcolor: #000;\t/* Text color */\r\n");
      out.write("\t\tfont-size:1.0em; \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* #submenu a:hover{\r\n");
      out.write("\t\tcolor: #FFEE;\t/* Red color when the user moves the mouse over sub menu items */\r\n");
      out.write("\t} */\r\n");
      out.write("\t\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tvar menuAlignment = 'left';\t// Align menu to the left or right?\t\t\r\n");
      out.write("\tvar topMenuSpacer = 4; // Horizontal space(pixels) between the main menu items\t\r\n");
      out.write("\tvar activateSubOnClick = false; // if true-> Show sub menu items on click, if false, show submenu items onmouseover\r\n");
      out.write("\tvar leftAlignSubItems = false; \t// left align sub items t\r\n");
      out.write("\t\r\n");
      out.write("\tvar activeMenuItem = false;\t// Don't change this option. It should initially be false\r\n");
      out.write("\tvar activeTabIndex = 0;\t// Index of initial active tab\t(0 = first tab) - If the value below is set to true, it will override this one.\r\n");
      out.write("\tvar rememberActiveTabByCookie = true;\t// Set it to true if you want to be able to save active tab as cookie\r\n");
      out.write("\t\r\n");
      out.write("\tvar MSIE = navigator.userAgent.indexOf('MSIE')>=0?true:false;\r\n");
      out.write("\tvar Opera = navigator.userAgent.indexOf('Opera')>=0?true:false;\r\n");
      out.write("\tvar navigatorVersion = navigator.appVersion.replace(/.*?MSIE ([0-9]\\.[0-9]).*/g,'$1')/1;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction Get_Cookie(name) { \r\n");
      out.write("\t\t   var start = document.cookie.indexOf(name+\"=\"); \r\n");
      out.write("\t\t   var len = start+name.length+1; \r\n");
      out.write("\t\t   if ((!start) && (name != document.cookie.substring(5,name.length))) return null; \r\n");
      out.write("\t\t   if (start == -1) return null; \r\n");
      out.write("\t\t   var end = document.cookie.indexOf(\";\",len); \r\n");
      out.write("\t\t   if (end == -1) end = document.cookie.length; \r\n");
      out.write("\t\t   return unescape(document.cookie.substring(len,end)); \r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t// This function has been slightly modified\r\n");
      out.write("\t\tfunction Set_Cookie(name,value,expires,path,domain,secure) { \r\n");
      out.write("\t\t\texpires = expires * 60*60*24*1000;\r\n");
      out.write("\t\t\tvar today = new Date();\r\n");
      out.write("\t\t\tvar expires_date = new Date( today.getTime() + (expires) );\r\n");
      out.write("\t\t    var cookieString = name + \"=\" +escape(value) + \r\n");
      out.write("\t\t       ( (expires) ? \";expires=\" + expires_date.toGMTString() : \"\") + \r\n");
      out.write("\t\t       ( (path) ? \";path=\" + path : \"\") + \r\n");
      out.write("\t\t       ( (domain) ? \";domain=\" + domain : \"\") + \r\n");
      out.write("\t\t       ( (secure) ? \";secure\" : \"\"); \r\n");
      out.write("\t\t    document.cookie = cookieString; \r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction showHide()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(activeMenuItem){\r\n");
      out.write("\t\t\tactiveMenuItem.className = 'inactiveMenuItem'; \t\r\n");
      out.write("\t\t\tvar theId = activeMenuItem.id.replace(/[^0-9]/g,'');\r\n");
      out.write("\t\t\tdocument.getElementById('submenu_'+theId).style.display='none';\r\n");
      out.write("\t\t\tvar img = activeMenuItem.getElementsByTagName('IMG');\r\n");
      out.write("\t\t\tif(img.length>0)img[0].style.display='none';\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar img = this.getElementsByTagName('IMG');\r\n");
      out.write("\t\tif(img.length>0)img[0].style.display='inline';\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t activeMenuItem = this;\t\t\r\n");
      out.write("\t\tthis.className = 'activeMenuItem';\r\n");
      out.write("\t\tvar theId = this.id.replace(/[^0-9]/g,'');\r\n");
      out.write("\t\tdocument.getElementById('submenu_'+theId).style.display='block';\r\n");
      out.write("\t\t \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\tif(rememberActiveTabByCookie){\r\n");
      out.write("\t\t\tSet_Cookie('dhtmlgoodies_tab_menu_tabIndex','index: ' + (theId-1),100);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction initMenu()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar mainMenuObj = document.getElementById('mainMenu');\r\n");
      out.write("\t\tvar menuItems = mainMenuObj.getElementsByTagName('A');\r\n");
      out.write("\t\tif(document.all){\r\n");
      out.write("\t\t\tmainMenuObj.style.visibility = 'hidden';\r\n");
      out.write("\t\t\tdocument.getElementById('submenu').style.visibility='hidden';\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\tif(rememberActiveTabByCookie){\r\n");
      out.write("\t\t\tvar cookieValue = Get_Cookie('dhtmlgoodies_tab_menu_tabIndex') + '';\r\n");
      out.write("\t\t\tcookieValue = cookieValue.replace(/[^0-9]/g,'');\r\n");
      out.write("\t\t\tif(cookieValue.length>0 && cookieValue<menuItems.length){\r\n");
      out.write("\t\t\t\tactiveTabIndex = cookieValue/1;\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar currentLeftPos = 15;\r\n");
      out.write("\t\tfor(var no=0;no<menuItems.length;no++){\t\t\t\r\n");
      out.write("\t\t\tif(activateSubOnClick)menuItems[no].onclick = showHide; else menuItems[no].onmouseover = showHide;\r\n");
      out.write("\t\t\tmenuItems[no].id = 'mainMenuItem' + (no+1);\r\n");
      out.write("\t\t\tif(menuAlignment=='left')\r\n");
      out.write("\t\t\t\tmenuItems[no].style.left = currentLeftPos + 'px';\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\tmenuItems[no].style.right = currentLeftPos + 'px';\r\n");
      out.write("\t\t\tcurrentLeftPos = currentLeftPos + menuItems[no].offsetWidth + topMenuSpacer; \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar img = menuItems[no].getElementsByTagName('IMG');\r\n");
      out.write("\t\t\tif(img.length>0){\r\n");
      out.write("\t\t\t\timg[0].style.display='none';\r\n");
      out.write("\t\t\t\tif(MSIE && !Opera && navigatorVersion<7){\r\n");
      out.write("\t\t\t\t\timg[0].style.bottom = '-1px';\r\n");
      out.write("\t\t\t\t\timg[0].style.right = '-1px';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tif(no==activeTabIndex){\r\n");
      out.write("\t\t\t\tmenuItems[no].className='activeMenuItem';\r\n");
      out.write("\t\t\t\tactiveMenuItem = menuItems[no];\r\n");
      out.write("\t\t\t\tvar img = activeMenuItem.getElementsByTagName('');\r\n");
      out.write("\t\t\t\tif(img.length>0)img[0].style.display='inline';\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t}else menuItems[no].className='inactiveMenuItem';\r\n");
      out.write("\t\t\tif(!document.all)menuItems[no].style.bottom = '-1px';\r\n");
      out.write("\t\t\tif(MSIE && navigatorVersion < 6)menuItems[no].style.bottom = '-2px';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar mainMenuLinks = mainMenuObj.getElementsByTagName('A');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar subCounter = 1;\r\n");
      out.write("\t\tvar parentWidth = mainMenuObj.offsetWidth;\r\n");
      out.write("\t\twhile(document.getElementById('submenu_' + subCounter)){\r\n");
      out.write("\t\t\tvar subItem = document.getElementById('submenu_' + subCounter);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(leftAlignSubItems){\r\n");
      out.write("\t\t\t\t// No action\r\n");
      out.write("\t\t\t}else{\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\tvar leftPos = mainMenuLinks[subCounter-1].offsetLeft;\r\n");
      out.write("\t\t\t\tdocument.getElementById('submenu_'+subCounter).style.paddingLeft =  leftPos + 'px';\r\n");
      out.write("\t\t\t\tsubItem.style.position ='absolute';\r\n");
      out.write("\t\t\t\tif(subItem.offsetWidth > parentWidth){\r\n");
      out.write("\t\t\t\t\tleftPos = leftPos - Math.max(0,subItem.offsetWidth-parentWidth); \t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tsubItem.style.paddingLeft =  leftPos + 'px';\r\n");
      out.write("\t\t\t\tsubItem.style.position ='static';\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(subCounter==(activeTabIndex+1)){\r\n");
      out.write("\t\t\t\tsubItem.style.display='block';\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tsubItem.style.display='none';\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsubCounter++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.all){\r\n");
      out.write("\t\t\tmainMenuObj.style.visibility = 'visible';\r\n");
      out.write("\t\t\tdocument.getElementById('submenu').style.visibility='visible';\r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t\tdocument.getElementById('submenu').style.display='Red';\r\n");
      out.write("\t}\r\n");
      out.write("\twindow.onload = initMenu;\t\r\n");
      out.write("\tfunction openCal()\r\n");
      out.write("\t{\r\n");
      out.write("\t\twindow.open(\"my.jsp\",4,7);\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- This is the start of the menu -->\r\n");
      out.write("<table>\r\n");
      out.write("<div id=\"mainMenu\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td><br><a>AirIndia</a></td>\r\n");
      out.write("\t<td><br><a>KingFisher</a></td>\r\n");
      out.write("\t<td><br><a>BritishAirLines</a></td>\r\n");
      out.write("\t<td><br><a>AmericanAirLines</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</div>\r\n");
      out.write("</table>\r\n");
      out.write("<div id=\"submenu\">\r\n");
      out.write("\t<!-- The first sub menu -->\r\n");
      out.write("\t<div id=\"submenu_1\">\r\n");
      out.write("\t<textarea rows=\"5\" cols=\"30\" style='visibility'>\r\n");
      out.write("Flight from Delhi\r\n");
      out.write(" to Hyderabad time \r\n");
      out.write("  Morning 10 am\r\n");
      out.write("</textarea>\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">Hyderabad</a><br>\r\n");
      out.write("\t\t<!--  <a href=\"javascript:openCal()\">Delhi</a><br>\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">Mumbai</a> -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Second sub menu -->\r\n");
      out.write("\t<div id=\"submenu_2\">\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">Mumbai</a><br>\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">Hyderabad</a><br>\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">Bangalore</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Third sub menu -->\r\n");
      out.write("\t<div id=\"submenu_3\">\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">New Delhi</a><br>\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">Kuala Lumpur</a><br>\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">Tokyo</a><br>\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">Ottawa</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Fourth sub menu -->\r\n");
      out.write("\t<div id=\"submenu_4\">\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">Sidny</a><br>\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">New Delhi</a><br>\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">London</a><br>\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">Moscow</a><br>\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">Beijil</a><br>\r\n");
      out.write("\t\t<a href=\"javascript:openCal()\">TokyoIslamabad</a><br>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
